-- Enable Row Level Security on all tables
-- Run this in Supabase SQL Editor

-- Create profiles table
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for profiles
-- Users can read their own profile
CREATE POLICY "Users can read own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

-- Users can insert their own profile
CREATE POLICY "Users can insert own profile" ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- Users can update their own profile
CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Create polls table
CREATE TABLE polls (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('multiple', 'yesno')),
  category TEXT NOT NULL,
  duration_end TIMESTAMP WITH TIME ZONE,
  creator_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  creator_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  vote_count INTEGER DEFAULT 0
);

-- Enable RLS on polls
ALTER TABLE polls ENABLE ROW LEVEL SECURITY;

-- RLS Policies for polls
-- Anyone can read polls
CREATE POLICY "Anyone can read polls" ON polls
  FOR SELECT USING (true);

-- Only authenticated users can insert polls
CREATE POLICY "Authenticated users can create polls" ON polls
  FOR INSERT WITH CHECK (auth.uid() = creator_id);

-- Only the creator can update their own polls
CREATE POLICY "Creators can update own polls" ON polls
  FOR UPDATE USING (auth.uid() = creator_id);

-- Only the creator can delete their own polls
CREATE POLICY "Creators can delete own polls" ON polls
  FOR DELETE USING (auth.uid() = creator_id);

-- Create votes table
CREATE TABLE votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id UUID NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  guest_id TEXT,
  option_index INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Unique constraint to prevent multiple votes per poll per user/guest
ALTER TABLE votes ADD CONSTRAINT unique_vote_per_poll_user
  EXCLUDE (poll_id WITH =, user_id WITH =) WHERE (user_id IS NOT NULL);

ALTER TABLE votes ADD CONSTRAINT unique_vote_per_poll_guest
  EXCLUDE (poll_id WITH =, guest_id WITH =) WHERE (guest_id IS NOT NULL);

-- Enable RLS on votes
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

-- RLS Policies for votes
-- Anyone can SELECT votes
CREATE POLICY "Anyone can read votes" ON votes
  FOR SELECT USING (true);

-- Anyone can INSERT votes if not already voted (WITH CHECK prevents duplicates)
CREATE POLICY "Anyone can insert votes if not already voted" ON votes
  FOR INSERT WITH CHECK (
    CASE
      WHEN user_id IS NOT NULL THEN NOT EXISTS (
        SELECT 1 FROM votes WHERE poll_id = votes.poll_id AND user_id = votes.user_id
      )
      WHEN guest_id IS NOT NULL THEN NOT EXISTS (
        SELECT 1 FROM votes WHERE poll_id = votes.poll_id AND guest_id = votes.guest_id
      )
      ELSE false
    END
  );

-- Only the voter can DELETE their own vote (for future undo feature)
CREATE POLICY "Users can delete own votes" ON votes
  FOR DELETE USING (
    CASE
      WHEN user_id IS NOT NULL THEN auth.uid() = user_id
      WHEN guest_id IS NOT NULL THEN true  -- Guests can delete, but we'll handle via localStorage
      ELSE false
    END
  );

-- Optional: Index for performance
CREATE INDEX idx_polls_creator_id ON polls(creator_id);
CREATE INDEX idx_polls_category ON polls(category);
CREATE INDEX idx_polls_created_at ON polls(created_at DESC);
CREATE INDEX idx_polls_duration_end ON polls(duration_end) WHERE duration_end IS NOT NULL;

-- Index for votes
CREATE INDEX idx_votes_poll_id ON votes(poll_id);
CREATE INDEX idx_votes_user_id ON votes(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_votes_guest_id ON votes(guest_id) WHERE guest_id IS NOT NULL;
CREATE INDEX idx_votes_created_at ON votes(created_at DESC);
